[MAPR-20440][Hue 3.9] AttributeError at /oozie/submit_workflow/1 'module' object has no attribute 'SECURITY_ENABLED' (cherry picked from commit ecdd711)